# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: objectProximityDetectionService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'objectProximityDetectionService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%objectProximityDetectionService.proto\"U\n\x1fObjectProximityDetectionRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12!\n\x19object_proximity_distance\x18\x02 \x01(\x05\"0\n\x1dObjectProximityDetectionReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x7f\n\x1fObjectProximityDetectionService\x12\\\n\x18ObjectProximityDetection\x12 .ObjectProximityDetectionRequest\x1a\x1e.ObjectProximityDetectionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objectProximityDetectionService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTPROXIMITYDETECTIONREQUEST']._serialized_start=41
  _globals['_OBJECTPROXIMITYDETECTIONREQUEST']._serialized_end=126
  _globals['_OBJECTPROXIMITYDETECTIONREPLY']._serialized_start=128
  _globals['_OBJECTPROXIMITYDETECTIONREPLY']._serialized_end=176
  _globals['_OBJECTPROXIMITYDETECTIONSERVICE']._serialized_start=178
  _globals['_OBJECTPROXIMITYDETECTIONSERVICE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
