// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: modemCommunication.proto
// Protobuf C++ Version: 5.27.2

#include "modemCommunication.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace modemCommunication {

inline constexpr ModemCommunicationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        contact_number_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ModemCommunicationRequest::ModemCommunicationRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ModemCommunicationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModemCommunicationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModemCommunicationRequestDefaultTypeInternal() {}
  union {
    ModemCommunicationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModemCommunicationRequestDefaultTypeInternal _ModemCommunicationRequest_default_instance_;

inline constexpr ModemCommunicationReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ModemCommunicationReply::ModemCommunicationReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ModemCommunicationReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModemCommunicationReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModemCommunicationReplyDefaultTypeInternal() {}
  union {
    ModemCommunicationReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModemCommunicationReplyDefaultTypeInternal _ModemCommunicationReply_default_instance_;
}  // namespace modemCommunication
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_modemCommunication_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_modemCommunication_2eproto = nullptr;
const ::uint32_t
    TableStruct_modemCommunication_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::modemCommunication::ModemCommunicationRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::modemCommunication::ModemCommunicationRequest, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::modemCommunication::ModemCommunicationRequest, _impl_.contact_number_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::modemCommunication::ModemCommunicationReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::modemCommunication::ModemCommunicationReply, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::modemCommunication::ModemCommunicationRequest)},
        {10, -1, -1, sizeof(::modemCommunication::ModemCommunicationReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::modemCommunication::_ModemCommunicationRequest_default_instance_._instance,
    &::modemCommunication::_ModemCommunicationReply_default_instance_._instance,
};
const char descriptor_table_protodef_modemCommunication_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030modemCommunication.proto\022\022modemCommuni"
    "cation\"D\n\031ModemCommunicationRequest\022\017\n\007m"
    "essage\030\001 \001(\t\022\026\n\016contact_number\030\002 \001(\005\"*\n\027"
    "ModemCommunicationReply\022\017\n\007message\030\001 \001(\t"
    "2\215\001\n\031ModemCommunicationService\022p\n\022ModemC"
    "ommunication\022-.modemCommunication.ModemC"
    "ommunicationRequest\032+.modemCommunication"
    ".ModemCommunicationReplyb\006proto3"
};
static ::absl::once_flag descriptor_table_modemCommunication_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_modemCommunication_2eproto = {
    false,
    false,
    312,
    descriptor_table_protodef_modemCommunication_2eproto,
    "modemCommunication.proto",
    &descriptor_table_modemCommunication_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_modemCommunication_2eproto::offsets,
    file_level_enum_descriptors_modemCommunication_2eproto,
    file_level_service_descriptors_modemCommunication_2eproto,
};
namespace modemCommunication {
// ===================================================================

class ModemCommunicationRequest::_Internal {
 public:
};

ModemCommunicationRequest::ModemCommunicationRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:modemCommunication.ModemCommunicationRequest)
}
inline PROTOBUF_NDEBUG_INLINE ModemCommunicationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::modemCommunication::ModemCommunicationRequest& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ModemCommunicationRequest::ModemCommunicationRequest(
    ::google::protobuf::Arena* arena,
    const ModemCommunicationRequest& from)
    : ::google::protobuf::Message(arena) {
  ModemCommunicationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.contact_number_ = from._impl_.contact_number_;

  // @@protoc_insertion_point(copy_constructor:modemCommunication.ModemCommunicationRequest)
}
inline PROTOBUF_NDEBUG_INLINE ModemCommunicationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ModemCommunicationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.contact_number_ = {};
}
ModemCommunicationRequest::~ModemCommunicationRequest() {
  // @@protoc_insertion_point(destructor:modemCommunication.ModemCommunicationRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ModemCommunicationRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ModemCommunicationRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ModemCommunicationRequest, _impl_._cached_size_),
              false,
          },
          &ModemCommunicationRequest::MergeImpl,
          &ModemCommunicationRequest::kDescriptorMethods,
          &descriptor_table_modemCommunication_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 60, 2> ModemCommunicationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ModemCommunicationRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::modemCommunication::ModemCommunicationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 contact_number = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ModemCommunicationRequest, _impl_.contact_number_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ModemCommunicationRequest, _impl_.contact_number_)}},
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ModemCommunicationRequest, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(ModemCommunicationRequest, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 contact_number = 2;
    {PROTOBUF_FIELD_OFFSET(ModemCommunicationRequest, _impl_.contact_number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\54\7\0\0\0\0\0\0"
    "modemCommunication.ModemCommunicationRequest"
    "message"
  }},
};

PROTOBUF_NOINLINE void ModemCommunicationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:modemCommunication.ModemCommunicationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.contact_number_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ModemCommunicationRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:modemCommunication.ModemCommunicationRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "modemCommunication.ModemCommunicationRequest.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 contact_number = 2;
  if (this->_internal_contact_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_contact_number(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:modemCommunication.ModemCommunicationRequest)
  return target;
}

::size_t ModemCommunicationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:modemCommunication.ModemCommunicationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // int32 contact_number = 2;
  if (this->_internal_contact_number() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_contact_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ModemCommunicationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModemCommunicationRequest*>(&to_msg);
  auto& from = static_cast<const ModemCommunicationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:modemCommunication.ModemCommunicationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_contact_number() != 0) {
    _this->_impl_.contact_number_ = from._impl_.contact_number_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModemCommunicationRequest::CopyFrom(const ModemCommunicationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:modemCommunication.ModemCommunicationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModemCommunicationRequest::InternalSwap(ModemCommunicationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.contact_number_, other->_impl_.contact_number_);
}

::google::protobuf::Metadata ModemCommunicationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ModemCommunicationReply::_Internal {
 public:
};

ModemCommunicationReply::ModemCommunicationReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:modemCommunication.ModemCommunicationReply)
}
inline PROTOBUF_NDEBUG_INLINE ModemCommunicationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::modemCommunication::ModemCommunicationReply& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ModemCommunicationReply::ModemCommunicationReply(
    ::google::protobuf::Arena* arena,
    const ModemCommunicationReply& from)
    : ::google::protobuf::Message(arena) {
  ModemCommunicationReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:modemCommunication.ModemCommunicationReply)
}
inline PROTOBUF_NDEBUG_INLINE ModemCommunicationReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ModemCommunicationReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ModemCommunicationReply::~ModemCommunicationReply() {
  // @@protoc_insertion_point(destructor:modemCommunication.ModemCommunicationReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ModemCommunicationReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ModemCommunicationReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ModemCommunicationReply, _impl_._cached_size_),
              false,
          },
          &ModemCommunicationReply::MergeImpl,
          &ModemCommunicationReply::kDescriptorMethods,
          &descriptor_table_modemCommunication_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 58, 2> ModemCommunicationReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ModemCommunicationReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::modemCommunication::ModemCommunicationReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ModemCommunicationReply, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(ModemCommunicationReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\52\7\0\0\0\0\0\0"
    "modemCommunication.ModemCommunicationReply"
    "message"
  }},
};

PROTOBUF_NOINLINE void ModemCommunicationReply::Clear() {
// @@protoc_insertion_point(message_clear_start:modemCommunication.ModemCommunicationReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ModemCommunicationReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:modemCommunication.ModemCommunicationReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "modemCommunication.ModemCommunicationReply.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:modemCommunication.ModemCommunicationReply)
  return target;
}

::size_t ModemCommunicationReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:modemCommunication.ModemCommunicationReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ModemCommunicationReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModemCommunicationReply*>(&to_msg);
  auto& from = static_cast<const ModemCommunicationReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:modemCommunication.ModemCommunicationReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModemCommunicationReply::CopyFrom(const ModemCommunicationReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:modemCommunication.ModemCommunicationReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModemCommunicationReply::InternalSwap(ModemCommunicationReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata ModemCommunicationReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace modemCommunication
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_modemCommunication_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
