// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: modemCommunication.proto
#ifndef GRPC_modemCommunication_2eproto__INCLUDED
#define GRPC_modemCommunication_2eproto__INCLUDED

#include "modemCommunication.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace modemCommunication {

class ModemCommunicationService final {
 public:
  static constexpr char const* service_full_name() {
    return "modemCommunication.ModemCommunicationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::modemCommunication::ModemCommunicationReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::modemCommunication::ModemCommunicationReply>> AsyncModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::modemCommunication::ModemCommunicationReply>>(AsyncModemCommunicationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::modemCommunication::ModemCommunicationReply>> PrepareAsyncModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::modemCommunication::ModemCommunicationReply>>(PrepareAsyncModemCommunicationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::modemCommunication::ModemCommunicationReply>* AsyncModemCommunicationRaw(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::modemCommunication::ModemCommunicationReply>* PrepareAsyncModemCommunicationRaw(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::modemCommunication::ModemCommunicationReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>> AsyncModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>>(AsyncModemCommunicationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>> PrepareAsyncModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>>(PrepareAsyncModemCommunicationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response, std::function<void(::grpc::Status)>) override;
      void ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>* AsyncModemCommunicationRaw(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>* PrepareAsyncModemCommunicationRaw(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ModemCommunication_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ModemCommunication(::grpc::ServerContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ModemCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ModemCommunication() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ModemCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModemCommunication(::grpc::ServerContext* /*context*/, const ::modemCommunication::ModemCommunicationRequest* /*request*/, ::modemCommunication::ModemCommunicationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestModemCommunication(::grpc::ServerContext* context, ::modemCommunication::ModemCommunicationRequest* request, ::grpc::ServerAsyncResponseWriter< ::modemCommunication::ModemCommunicationReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ModemCommunication<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ModemCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ModemCommunication() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response) { return this->ModemCommunication(context, request, response); }));}
    void SetMessageAllocatorFor_ModemCommunication(
        ::grpc::MessageAllocator< ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ModemCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModemCommunication(::grpc::ServerContext* /*context*/, const ::modemCommunication::ModemCommunicationRequest* /*request*/, ::modemCommunication::ModemCommunicationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ModemCommunication(
      ::grpc::CallbackServerContext* /*context*/, const ::modemCommunication::ModemCommunicationRequest* /*request*/, ::modemCommunication::ModemCommunicationReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ModemCommunication<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ModemCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ModemCommunication() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ModemCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModemCommunication(::grpc::ServerContext* /*context*/, const ::modemCommunication::ModemCommunicationRequest* /*request*/, ::modemCommunication::ModemCommunicationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ModemCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ModemCommunication() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ModemCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModemCommunication(::grpc::ServerContext* /*context*/, const ::modemCommunication::ModemCommunicationRequest* /*request*/, ::modemCommunication::ModemCommunicationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestModemCommunication(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ModemCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ModemCommunication() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ModemCommunication(context, request, response); }));
    }
    ~WithRawCallbackMethod_ModemCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModemCommunication(::grpc::ServerContext* /*context*/, const ::modemCommunication::ModemCommunicationRequest* /*request*/, ::modemCommunication::ModemCommunicationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ModemCommunication(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ModemCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ModemCommunication() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply>* streamer) {
                       return this->StreamedModemCommunication(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ModemCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ModemCommunication(::grpc::ServerContext* /*context*/, const ::modemCommunication::ModemCommunicationRequest* /*request*/, ::modemCommunication::ModemCommunicationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedModemCommunication(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::modemCommunication::ModemCommunicationRequest,::modemCommunication::ModemCommunicationReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ModemCommunication<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ModemCommunication<Service > StreamedService;
};

}  // namespace modemCommunication


#endif  // GRPC_modemCommunication_2eproto__INCLUDED
