// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: modemCommunication.proto

#include "modemCommunication.pb.h"
#include "modemCommunication.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace modemCommunication {

static const char* ModemCommunicationService_method_names[] = {
  "/modemCommunication.ModemCommunicationService/ModemCommunication",
};

std::unique_ptr< ModemCommunicationService::Stub> ModemCommunicationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ModemCommunicationService::Stub> stub(new ModemCommunicationService::Stub(channel, options));
  return stub;
}

ModemCommunicationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ModemCommunication_(ModemCommunicationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ModemCommunicationService::Stub::ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::modemCommunication::ModemCommunicationReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ModemCommunication_, context, request, response);
}

void ModemCommunicationService::Stub::async::ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModemCommunication_, context, request, response, std::move(f));
}

void ModemCommunicationService::Stub::async::ModemCommunication(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModemCommunication_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>* ModemCommunicationService::Stub::PrepareAsyncModemCommunicationRaw(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::modemCommunication::ModemCommunicationReply, ::modemCommunication::ModemCommunicationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ModemCommunication_, context, request);
}

::grpc::ClientAsyncResponseReader< ::modemCommunication::ModemCommunicationReply>* ModemCommunicationService::Stub::AsyncModemCommunicationRaw(::grpc::ClientContext* context, const ::modemCommunication::ModemCommunicationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncModemCommunicationRaw(context, request, cq);
  result->StartCall();
  return result;
}

ModemCommunicationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModemCommunicationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModemCommunicationService::Service, ::modemCommunication::ModemCommunicationRequest, ::modemCommunication::ModemCommunicationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModemCommunicationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::modemCommunication::ModemCommunicationRequest* req,
             ::modemCommunication::ModemCommunicationReply* resp) {
               return service->ModemCommunication(ctx, req, resp);
             }, this)));
}

ModemCommunicationService::Service::~Service() {
}

::grpc::Status ModemCommunicationService::Service::ModemCommunication(::grpc::ServerContext* context, const ::modemCommunication::ModemCommunicationRequest* request, ::modemCommunication::ModemCommunicationReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace modemCommunication

